apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Twilight4/movie-review-platform.git
    targetRevision: HEAD
    path: k8s/overlays/base/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=True
    automated:
      prune: true
      selfHeal: true
