apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - movie-api-deployment.yaml
  - movie-api-service.yaml
  - movie-api-hpa.yaml
  - ingress.yaml
  - ingress-nginx-namespace.yaml
  - configmap.yaml
  - cosmos-service.yaml
  - secret.yaml
  - netpol.yaml

commonLabels:
  app: movie-api
