name: image-ci

on:
  push:
    branches: ["main"]
    tags: "[0-9]*.[0-9]*.[0-9]*"
    paths:
      - "app/**/*"  # only rebuild when app code changes

jobs:
  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate-image-tag.outputs.image_tag }}     # the image tag itself
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Necessary to get all tags for IMAGE_TAG generation with git describe
          fetch-depth: 0

      # Install task
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      # Generate image tag
      - name: Generate Image Tag
        id: generate-image-tag
        working-directory: .github/actions
        run: |
          image_tag=$(task generate-version-tag)
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

      # Build image
      - name: Build Image
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}    # pull in that image tag from the previous job
        working-directory: ./app
        run: |
          task build-container-image IMAGE_TAG=${IMAGE_TAG}

      # Log in to GCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Push image
      - name: Push image
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}
        working-directory: ./app
        run: |
          task push-container-image IMAGE_TAG=${IMAGE_TAG}
